# Services definition for building & deploying

x-common:

  app:
    environment: &app_environment
      DISCORD_TOKEN: ${DISCORD_TOKEN:-}

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${IMAGES_TAG:-latest}
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        <<: [ *app_environment ]
    # Deploy
    environment:
      <<: [ *app_environment ]
